apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: e-ticket/payment-service
          ports:
            - containerPort: 50053
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
          env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: STRIPE_API_KEY
                  name: stripe-secrets
            - name: STRIPE_SUCCESS_URL
              valueFrom:
                configMapKeyRef:
                  key: STRIPE_SUCCESS_URL
                  name: app-config
            - name: STRIPE_CANCEL_URL
              valueFrom:
                configMapKeyRef:
                  key: STRIPE_CANCEL_URL
                  name: app-config
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key: STRIPE_WEBHOOK_SECRET
                  name: stripe-secrets
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  key: payment_db_uri
                  name: db-credentials
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: rabbitmq-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 50053
      name: grpc
      targetPort: 50053
  type: ClusterIP
